export const products: IProduct[] = [
  {
    id: '1',
    name: 'Premium Wireless Headphones',
    description:
      'High-quality wireless headphones with noise cancellation and 30-hour battery life',
    price: 299.99,
    image: '/api/media/product--1.webp',
  },
  {
    id: '2',
    name: 'Smart Fitness Watch',
    description: 'Advanced fitness tracker with heart rate monitoring and GPS',
    price: 199.99,
    image: '/api/media/product--2.webp',
  },
  {
    id: '3',
    name: 'Portable Bluetooth Speaker',
    description: 'Waterproof speaker with 360° sound and 12-hour playback',
    price: 79.99,
    image: '/api/media/product--3.webp',
  },
  {
    id: '4',
    name: 'Ultra HD Webcam',
    description: '4K webcam with auto light correction and noise-canceling microphone',
    price: 129.99,
    image: '/api/media/product--4.webp',
  },
  {
    id: '5',
    name: 'Mechanical Gaming Keyboard',
    description: 'RGB mechanical keyboard with customizable switches',
    price: 149.99,
    image: '/api/media/product--5.webp',
  },
  {
    id: '6',
    name: 'Wireless Gaming Mouse',
    description: 'High-precision gaming mouse with adjustable DPI',
    price: 89.99,
    image: '/api/media/product--6.webp',
  },
  {
    id: '7',
    name: 'External SSD 1TB',
    description: 'Ultra-fast external SSD with USB-C connectivity',
    price: 199.99,
    image: '/api/media/product--7.webp',
  },
  {
    id: '8',
    name: 'Smart Home Hub',
    description: 'Central control unit for all your smart home devices',
    price: 159.99,
    image: '/api/media/product--8.webp',
  },
  {
    id: '9',
    name: '4K Monitor 27"',
    description: 'Ultra HD monitor with HDR support',
    price: 399.99,
    image: '/api/media/product--9.webp',
  },
  {
    id: '10',
    name: 'Wireless Charging Pad',
    description: 'Fast wireless charging pad for multiple devices',
    price: 49.99,
    image: '/api/media/product--10.webp',
  },
  {
    id: '11',
    name: 'Smart Doorbell',
    description: 'HD video doorbell with motion detection',
    price: 179.99,
    image: '/api/media/product--11.webp',
  },
  {
    id: '12',
    name: 'Portable Power Bank',
    description: '20000mAh power bank with fast charging',
    price: 69.99,
    image: '/api/media/product--12.webp',
  },
  {
    id: '13',
    name: 'Smart LED Strip',
    description: 'RGB LED strip with voice control compatibility',
    price: 39.99,
    image: '/api/media/product--13.webp',
  },
  {
    id: '14',
    name: 'Wireless Earbuds',
    description: 'True wireless earbuds with active noise cancellation',
    price: 159.99,
    image: '/api/media/product--14.webp',
  },
  {
    id: '15',
    name: 'Smart Thermostat',
    description: 'Energy-saving smart thermostat with remote control',
    price: 129.99,
    image: '/api/media/product--15.webp',
  },
  {
    id: '16',
    name: 'Gaming Headset',
    description: '7.1 surround sound gaming headset with microphone',
    price: 119.99,
    image: '/api/media/product--16.webp',
  },
  {
    id: '17',
    name: 'Smart Security Camera',
    description: '1080p security camera with night vision',
    price: 89.99,
    image: '/api/media/product--17.webp',
  },
  {
    id: '18',
    name: 'USB-C Hub',
    description: '10-in-1 USB-C hub with 4K display support',
    price: 59.99,
    image: '/api/media/product--18.webp',
  },
  {
    id: '19',
    name: 'Smart Light Bulb',
    description: 'Color-changing smart bulb with app control',
    price: 29.99,
    image: '/api/media/product--19.webp',
  },
  {
    id: '20',
    name: 'Portable Projector',
    description: '1080p portable projector with built-in speaker',
    price: 299.99,
    image: '/api/media/product--20.webp',
  },
  {
    id: '21',
    name: 'Wireless Keyboard',
    description: 'Slim wireless keyboard with long battery life',
    price: 49.99,
    image: '/api/media/product--21.webp',
  },
  {
    id: '22',
    name: 'Smart Scale',
    description: 'Body composition scale with smartphone sync',
    price: 79.99,
    image: '/api/media/product--22.webp',
  },
  {
    id: '23',
    name: 'Bluetooth Car Adapter',
    description: 'Hands-free car adapter with voice control',
    price: 39.99,
    image: '/api/media/product--23.webp',
  },
  {
    id: '24',
    name: 'Smart Plug',
    description: 'WiFi-enabled smart plug with energy monitoring',
    price: 24.99,
    image: '/api/media/product--24.webp',
  },
];
